#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


./binaryBreakup/Allclean
./breakup/Allclean
./coalescence/Allclean
./coalescenceAndBreakup/Allclean
./expansion/Allclean
./uniformGrowth/Allclean