#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

foamCleanCase -case ./boundaryLaunderSharma
foamCleanCase -case ./boundaryNonNewtonian
foamCleanCase -case ./boundaryWallFunctions
foamCleanCase -case ./boundaryWallFunctionsProfile