#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

cmake -S "./Test-fvMeshTools" -B "./Test-fvMeshTools/build" "-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE" "-DCMAKE_PREFIX_PATH=$MIKENO_BINARY_INSTALL_PREFIX" "-DCMAKE_CXX_COMPILER=$WM_CXX"
cmake --build Test-fvMeshTools/build


export PATH="$PATH:$(pwd)/Test-fvMeshTools/build"

./cavity/Allrun