#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


runApplication blockMesh
export ENV_EOS=PengRobinsonGas
runApplication -s $ENV_EOS Test-cubicEOS -eos $ENV_EOS
export ENV_EOS=RedlichKwongGas
runApplication -s $ENV_EOS Test-cubicEOS -eos $ENV_EOS