#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cmake -S . -B build "-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE" "-DCMAKE_PREFIX_PATH=$MIKENO_BINARY_INSTALL_PREFIX" "-DCMAKE_CXX_COMPILER=$WM_CXX"
cmake --build build

export PATH="$PATH:$(pwd)/build"

./pure/Allrun
./Mix/Allrun
