#!/bin/sh

# shellcheck disable=SC3028 disable=SC3054
cur_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

"$cur_dir/heatTransferLimitedPhaseChange/waterEvaporation/Allclean"
"$cur_dir/massDiffusionLimitedPhaseChange/waterEvaporation/Allclean"
"$cur_dir/massDiffusionLimitedPhaseChange/waterAndIsopropanolEvaporation/Allclean"

"$cur_dir/populationBalance/Allclean"