#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

./heatTransferLimitedPhaseChange/waterEvaporation/Allclean
./massDiffusionLimitedPhaseChange/waterEvaporation/Allclean
./massDiffusionLimitedPhaseChange/waterAndIsopropanolEvaporation/Allclean

./populationBalance/Allclean