#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

./heatTransferLimitedPhaseChange/waterEvaporation/Allrun
./massDiffusionLimitedPhaseChange/waterEvaporation/Allrun
./massDiffusionLimitedPhaseChange/waterAndIsopropanolEvaporation/Allrun

./populationBalance/Allrun