#!/bin/sh


twoPhaseModels/Allwmake $targetType $*
multiphaseModels/Allwmake $targetType $*
MomentumTransportModels/Allwmake $targetType $*
ThermophysicalTransportModels/Allwmake $targetType $*
wmake $targetType radiationModels
wmake $targetType combustionModels
mesh/Allwmake $targetType $*
renumber/Allwmake $targetType $*
fvAgglomerationMethods/Allwmake $targetType $*
wmake $targetType fvMotionSolver

wmake $targetType fvConstraints

fvModels/Allwmake $targetType $*
functionObjects/Allwmake $targetType $*

lagrangian/Allwmake $targetType $*
Lagrangian/Allwmake $targetType $*
rigidBodyMotion/Allwmake $targetType $*

wmake $targetType fvModels/propellerDisk
wmake $targetType fvModels/rigidBodyPropellerDisk

wmake $targetType specieTransfer
wmake $targetType atmosphericModels
wmake $targetType waves


#------------------------------------------------------------------------------
