#!/bin/sh

wmake $targetType fvConstraints

fvModels/Allwmake $targetType $*
functionObjects/Allwmake $targetType $*

lagrangian/Allwmake $targetType $*
Lagrangian/Allwmake $targetType $*
rigidBodyMotion/Allwmake $targetType $*

wmake $targetType fvModels/propellerDisk
wmake $targetType fvModels/rigidBodyPropellerDisk

wmake $targetType specieTransfer
wmake $targetType atmosphericModels
wmake $targetType waves


#------------------------------------------------------------------------------
