#!/bin/sh

lagrangian/Allwmake $targetType $*
Lagrangian/Allwmake $targetType $*
rigidBodyMotion/Allwmake $targetType $*

wmake $targetType fvModels/propellerDisk
wmake $targetType fvModels/rigidBodyPropellerDisk

wmake $targetType specieTransfer
wmake $targetType atmosphericModels
wmake $targetType waves


#------------------------------------------------------------------------------
